apiVersion: v1
kind: Service
metadata:
  name: {{ include "scarlettbytes.fullname" . }}-web
  labels:
    {{- include "scarlettbytes.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}c
      protocol: TCP
      name: http
  selector:
    {{- include "scarlettbytes.selectorLabels.web" . | nindent 4 }}
